# Use a base image
FROM nginx:alpine

# Copy your HTML and CSS files into the container
COPY website.html /usr/share/nginx/html
COPY task.css /usr/share/nginx/html/css/

# Expose port 80 (the default port for HTTP)
EXPOSE 80

